server:
  port: 9093

spring:
  application:
    name: JasonYan.project.third

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.18:9092/eureka/

  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}

#    healthcheck:
#      enabled: true
